---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: plex
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      run: plex
  template:
    metadata:
      labels:
        run: plex
    spec:
      securityContext:
        fsGroup: 1000
      hostNetwork: true  # Required to get local apps to hit correct interfaces :yuck:
      containers:
      - env:
        - name: TZ
          value: Pacific/Auckland
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        image: linuxserver/plex
        name: plex
        ports:
        - containerPort: 32400
          name: webui
          protocol: TCP
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: plex
        - mountPath: /data/tv 
          name: htpc-home
          subPath: media/tv  
        - mountPath: /data/movies 
          name: htpc-home
          subPath: media/movies
