apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: htpc
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: emby
            port:
              number: 8096
      - path: /jackett
        pathType: Exact
        backend:
          service:
            name: jackett
            port:
              number: 9117
      - path: /sonarr
        pathType: Exact
        backend:
          service:
            name: sonarr
            port:
              number: 8989
      - path: /radarr
        pathType: Exact
        backend:
          service:
            name: radarr
            port:
              number: 7878
      - path: /bazarr
        pathType: Exact
        backend:
          service:
            name: bazarr
            port:
              number: 6767
      - path: /transmission
        pathType: Exact
        backend:
          service:
            name: transmission
            port:
              number: 9091
